version: 0.0
os: linux
files:
  - source: /
    destination: /opt/health-intelligence
    overwrite: yes
    pattern: "**/*"
permissions:
  - object: /opt/health-intelligence
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /opt/health-intelligence/deploy.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /opt/health-intelligence/start_server.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /opt/health-intelligence/stop_server.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 600
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user