version: '3.8'

services:
  # Health Intelligence API
  api:
    image: ${ECR_API_REPO}:${API_IMAGE_TAG}
    container_name: health_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEWS_API_KEY: ${NEWS_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ENVIRONMENT: production
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ec2/health-intelligence
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream: api-${HOSTNAME}
        awslogs-create-group: "true"
    networks:
      - health_network

  # Dashboard (Custom image from ECR)
  dashboard:
    image: ${ECR_DASHBOARD_REPO}:${DASHBOARD_IMAGE_TAG}
    container_name: health_dashboard
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ec2/health-intelligence
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream: dashboard-${HOSTNAME}
        awslogs-create-group: "true"
    networks:
      - health_network

networks:
  health_network:
    driver: bridge